# Module: Pandas Assignments
## Lesson: Data Manipulation and Analysis with Pandas

### Assignment 1: Setup and Messy Dataset

Import `pandas` as `pd` and `numpy` as `np`. Then run the cell below. It creates a small sales dataset with **deliberately missing values** and saves it as `data.csv` (the lecture used a similar file). You will use `data.csv` for Parts 1-5.

The columns are `date`, `category`, `value`, `product`, `sales`, and `region`.

In [88]:
import pandas as pd
import numpy as np

rng = np.random.default_rng(42)
n_rows = 30

messy = pd.DataFrame(
    {
        "date": pd.date_range("2026-01-01", periods=n_rows).strftime("%Y-%m-%d"),
        "category": rng.choice(["A", "B", "C"], n_rows),
        "value": rng.integers(10, 100, n_rows).astype(float),
        "product": rng.choice(["Product1", "Product2", "Product3"], n_rows),
        "sales": rng.integers(100, 1000, n_rows).astype(float),
        "region": rng.choice(["East", "North", "South", "West"], n_rows),
    }
)

# punch holes: 3 missing in `value`, 4 missing in `sales`
messy.loc[rng.choice(n_rows, 3, replace=False), "value"] = np.nan
messy.loc[rng.choice(n_rows, 4, replace=False), "sales"] = np.nan

messy.to_csv("data.csv", index=False)

## Part 1: Loading and Exploring Data

### Assignment 2: Reading the CSV

Read `data.csv` into a DataFrame named `df` using `pd.read_csv`.

In [89]:
df = pd.read_csv("data.csv")

### Assignment 3: First and Last Rows

1. Display the first 5 rows using `df.head()`.
2. Display the last 5 rows using `df.tail()`.
3. Display the last 10 rows using `df.tail(10)`.

What does the number you pass as an argument control?

In [90]:
df.head()

         date category  value   product  sales region
0  2026-01-01        A   50.0  Product3  491.0  North
1  2026-01-02        C   30.0  Product3  824.0  South
2  2026-01-03        B   18.0  Product2  857.0  South
3  2026-01-04        B   59.0  Product3    NaN  North
4  2026-01-05        B   89.0  Product2  908.0   West

In [91]:
df.tail()

          date category  value   product  sales region
25  2026-01-26        B   13.0  Product3  611.0   West
26  2026-01-27        B   59.0  Product1  133.0   East
27  2026-01-28        C    NaN  Product1  225.0   East
28  2026-01-29        B   76.0  Product3  320.0   West
29  2026-01-30        B   71.0  Product3  203.0   East

In [92]:
df.tail(10)

          date category  value   product  sales region
20  2026-01-21        B   78.0  Product3  349.0   West
21  2026-01-22        B   27.0  Product2  802.0   East
22  2026-01-23        A   42.0  Product1  600.0  North
23  2026-01-24        C    NaN  Product3  513.0  North
24  2026-01-25        C   54.0  Product2  555.0   West
25  2026-01-26        B   13.0  Product3  611.0   West
26  2026-01-27        B   59.0  Product1  133.0   East
27  2026-01-28        C    NaN  Product1  225.0   East
28  2026-01-29        B   76.0  Product3  320.0   West
29  2026-01-30        B   71.0  Product3  203.0   East

### Assignment 4: Statistical Summary

Use `df.describe()`.
1. Which columns are included in the output? Why are the others left out?
2. Read off the mean, standard deviation, minimum, 25th, 50th, and 75th percentiles of `value` and `sales`.
3. Is the `count` of `value` the same as the count of `sales`? What does that tell you?

(Bonus: look up `df.describe(include="all")` and compare.)

In [93]:
df.describe()

           value       sales
count  27.000000   26.000000
mean   56.962963  531.153846
std    26.354800  255.836619
min    13.000000  106.000000
25%    35.500000  316.250000
50%    59.000000  539.500000
75%    78.000000  785.000000
max    97.000000  908.000000

In [94]:
df.dtypes

date            str
category        str
value       float64
product         str
sales       float64
region          str
dtype: object

In [95]:
df.isnull()

     date  category  value  product  sales  region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False   True   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False   True    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False  False   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False  False    False   True   False
16  False     False  False    False   True   False
17  False     False  False    False   True   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False   True    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False   True    False  False   False
28  False     False  False    False  False   False
29  False     False  False    False  False   False

In [96]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16     True
17     True
18    False
19    False
20    False
21    False
22    False
23     True
24    False
25    False
26    False
27     True
28    False
29    False
dtype: bool

### Assignment 5: Data Types

Print the data types of `df` using `df.dtypes`.
1. What is the data type of the `date` column? What does `object` (or `str` in newer pandas versions) mean here?
2. Why are `value` and `sales` `float64` even though they look like whole numbers?

In [97]:
df.dtypes

date            str
category        str
value       float64
product         str
sales       float64
region          str
dtype: object

In [98]:
# date is a string here

## Part 2: Handling Missing Values

### Assignment 6: Detecting Missing Values

Use `df.isnull()` and print the result. In the output, what does `True` mean and what does `False` mean? Why is it hard to find missing values just by looking at this output on a large dataset?

In [99]:
df.isnull()

     date  category  value  product  sales  region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False   True   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False   True    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False  False   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False  False    False   True   False
16  False     False  False    False   True   False
17  False     False  False    False   True   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False   True    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False   True    False  False   False
28  False     False  False    False  False   False
29  False     False  False    False  False   False

In [100]:
# True means the value is null
# False means the value is not null
# The data has a lot of rows and columns hence hard to find

### Assignment 7: Rows with Missing Values

Use `df.isnull().any(axis=1)` to get a True/False value for every row, telling whether that row has at least one missing value.
1. Use the result as a boolean mask to display only the rows that contain missing values.
2. What does `axis=1` mean here? What happens if you remove it (the default is `axis=0`)?

In [101]:
df.isnull().any(axis=1)  # The checks for any null value across all the columns per row

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16     True
17     True
18    False
19    False
20    False
21    False
22    False
23     True
24    False
25    False
26    False
27     True
28    False
29    False
dtype: bool

In [102]:
df.isnull().any()  # This checks every row per column. It it finds a null value in a column in any row it will output True.

date        False
category    False
value        True
product     False
sales        True
region      False
dtype: bool

In [103]:
df[df.isnull().any(
    axis=1)]  # If this finds in a row that a column value is null it includes that row in the data frame

          date category  value   product  sales region
3   2026-01-04        B   59.0  Product3    NaN  North
8   2026-01-09        A    NaN  Product1  673.0  South
15  2026-01-16        C   97.0  Product2    NaN  North
16  2026-01-17        B   50.0  Product1    NaN  South
17  2026-01-18        A   90.0  Product1    NaN   East
23  2026-01-24        C    NaN  Product3  513.0  North
27  2026-01-28        C    NaN  Product1  225.0   East

### Assignment 8: Counting Missing Values

Use `df.isnull().sum()` to count the missing values in every column. How many are missing in `value` and in `sales`? Why does `sum()` work on True/False values?

In [104]:
df.isnull().sum()  # hence here value column is a

date        0
category    0
value       3
product     0
sales       4
region      0
dtype: int64

### Assignment 9: Filling Missing Values with a Constant

Fill every missing value in the DataFrame with `0` using `fillna(0)`. Store the result in a **new** DataFrame named `df_zero` so the original `df` stays unchanged.

Print `df.isnull().sum()` and `df_zero.isnull().sum()`. Explain why filling with `0` is usually a poor choice for numerical columns such as `sales`.

In [105]:
df_zero = df.fillna(0)
df_zero

          date category  value   product  sales region
0   2026-01-01        A   50.0  Product3  491.0  North
1   2026-01-02        C   30.0  Product3  824.0  South
2   2026-01-03        B   18.0  Product2  857.0  South
3   2026-01-04        B   59.0  Product3    0.0  North
4   2026-01-05        B   89.0  Product2  908.0   West
5   2026-01-06        C   15.0  Product1  359.0  South
6   2026-01-07        A   87.0  Product3  315.0   East
7   2026-01-08        C   84.0  Product2  714.0   West
8   2026-01-09        A    0.0  Product1  673.0  South
9   2026-01-10        A   66.0  Product2  225.0  South
10  2026-01-11        B   24.0  Product3  849.0  South
11  2026-01-12        C   78.0  Product1  279.0  South
12  2026-01-13        C   73.0  Product2  824.0   East
13  2026-01-14        C   41.0  Product1  106.0  South
14  2026-01-15        C   16.0  Product3  817.0   West
15  2026-01-16        C   97.0  Product2    0.0  North
16  2026-01-17        B   50.0  Product1    0.0  South
17  2026-01-18        A   90.0  Product1    0.0   East
18  2026-01-19        C   71.0  Product2  524.0  North
19  2026-01-20        B   80.0  Product3  734.0  North
20  2026-01-21        B   78.0  Product3  349.0   West
21  2026-01-22        B   27.0  Product2  802.0   East
22  2026-01-23        A   42.0  Product1  600.0  North
23  2026-01-24        C    0.0  Product3  513.0  North
24  2026-01-25        C   54.0  Product2  555.0   West
25  2026-01-26        B   13.0  Product3  611.0   West
26  2026-01-27        B   59.0  Product1  133.0   East
27  2026-01-28        C    0.0  Product1  225.0   East
28  2026-01-29        B   76.0  Product3  320.0   West
29  2026-01-30        B   71.0  Product3  203.0   East

In [106]:
df_zero.isnull().any()

date        False
category    False
value       False
product     False
sales       False
region      False
dtype: bool

### Assignment 10: Filling Missing Values with the Mean

Create a new column `sales_fillna` in `df` by filling the missing values of `sales` with the mean of the `sales` column (`df["sales"].fillna(df["sales"].mean())`).

Display the `sales` and `sales_fillna` columns side by side. Check that the rows that were `NaN` now contain the mean, and that the other rows are unchanged.

In [107]:
sales_fillna = df["sales"].fillna(df["sales"].mean()).astype(int)

In [108]:
df["sales_fillna"] = sales_fillna

In [109]:
df

          date category  value   product  sales region  sales_fillna
0   2026-01-01        A   50.0  Product3  491.0  North           491
1   2026-01-02        C   30.0  Product3  824.0  South           824
2   2026-01-03        B   18.0  Product2  857.0  South           857
3   2026-01-04        B   59.0  Product3    NaN  North           531
4   2026-01-05        B   89.0  Product2  908.0   West           908
5   2026-01-06        C   15.0  Product1  359.0  South           359
6   2026-01-07        A   87.0  Product3  315.0   East           315
7   2026-01-08        C   84.0  Product2  714.0   West           714
8   2026-01-09        A    NaN  Product1  673.0  South           673
9   2026-01-10        A   66.0  Product2  225.0  South           225
10  2026-01-11        B   24.0  Product3  849.0  South           849
11  2026-01-12        C   78.0  Product1  279.0  South           279
12  2026-01-13        C   73.0  Product2  824.0   East           824
13  2026-01-14        C   41.0  Product1  106.0  South           106
14  2026-01-15        C   16.0  Product3  817.0   West           817
15  2026-01-16        C   97.0  Product2    NaN  North           531
16  2026-01-17        B   50.0  Product1    NaN  South           531
17  2026-01-18        A   90.0  Product1    NaN   East           531
18  2026-01-19        C   71.0  Product2  524.0  North           524
19  2026-01-20        B   80.0  Product3  734.0  North           734
20  2026-01-21        B   78.0  Product3  349.0   West           349
21  2026-01-22        B   27.0  Product2  802.0   East           802
22  2026-01-23        A   42.0  Product1  600.0  North           600
23  2026-01-24        C    NaN  Product3  513.0  North           513
24  2026-01-25        C   54.0  Product2  555.0   West           555
25  2026-01-26        B   13.0  Product3  611.0   West           611
26  2026-01-27        B   59.0  Product1  133.0   East           133
27  2026-01-28        C    NaN  Product1  225.0   East           225
28  2026-01-29        B   76.0  Product3  320.0   West           320
29  2026-01-30        B   71.0  Product3  203.0   East           203

In [110]:
value_fillna = df["value"].fillna(df["value"].mean()).astype(int)

In [111]:
df["value_fillna"] = value_fillna

In [112]:
df

,date,category,value,product,sales,region,sales_fillna,value_fillna
0,2026-01-01,A,50.0,Product3,491.0,North,491,50
1,2026-01-02,C,30.0,Product3,824.0,South,824,30
2,2026-01-03,B,18.0,Product2,857.0,South,857,18
3,2026-01-04,B,59.0,Product3,NaN,North,531,59
4,2026-01-05,B,89.0,Product2,908.0,West,908,89
5,2026-01-06,C,15.0,Product1,359.0,South,359,15
6,2026-01-07,A,87.0,Product3,315.0,East,315,87
7,2026-01-08,C,84.0,Product2,714.0,West,714,84
8,2026-01-09,A,NaN,Product1,673.0,South,673,56
9,2026-01-10,A,66.0,Product2,225.0,South,225,66
10,2026-01-11,B,24.0,Product3,849.0,South,849,24
11,2026-01-12,C,78.0,Product1,279.0,South,279,78
12,2026-01-13,C,73.0,Product2,824.0,East,824,73
13,2026-01-14,C,41.0,Product1,106.0,South,106,41
14,2026-01-15,C,16.0,Product3,817.0,West,817,16
15,2026-01-16,C,97.0,Product2,NaN,North,531,97
16,2026-01-17,B,50.0,Product1,NaN,South,531,50
17,2026-01-18,A,90.0,Product1,NaN,East,531,90
18,2026-01-19,C,71.0,Product2,524.0,North,524,71
19,2026-01-20,B,80.0,Product3,734.0,North,734,80
20,2026-01-21,B,78.0,Product3,349.0,West,349,78
21,2026-01-22,B,27.0,Product2,802.0,East,802,27
22,2026-01-23,A,42.0,Product1,600.0,North,600,42
23,2026-01-24,C,NaN,Product3,513.0,North,513,56
24,2026-01-25,C,54.0,Product2,555.0,West,555,54
25,2026-01-26,B,13.0,Product3,611.0,West,611,13
26,2026-01-27,B,59.0,Product1,133.0,East,133,59
27,2026-01-28,C,NaN,Product1,225.0,East,225,56
28,2026-01-29,B,76.0,Product3,320.0,West,320,76
29,2026-01-30,B,71.0,Product3,203.0,East,203,71

In [113]:
df["value_fillna"].astype(int)

0     50
1     30
2     18
3     59
4     89
5     15
6     87
7     84
8     56
9     66
10    24
11    78
12    73
13    41
14    16
15    97
16    50
17    90
18    71
19    80
20    78
21    27
22    42
23    56
24    54
25    13
26    59
27    56
28    76
29    71
Name: value_fillna, dtype: int64

### Assignment 11: Filling with Median and Mode

The mean is not always the best choice (it is sensitive to outliers).
1. Create `value_fillna_median` by filling the missing values in `value` with the median of the column.
2. Create `region_filled` by filling any missing values in `region` with its mode (`df["region"].mode()[0]`). (`region` has no missing values in this dataset; just make sure your code would work if it did.)
3. When would you prefer the median over the mean?

In [114]:
value_fillna_median = df["value"].fillna(df["value"].median())

In [115]:
region_filled = df["region"].fillna(df["region"].mode()[0])

In [116]:
df["value_fillna_median"] = value_fillna_median

In [117]:
df["region_filled"] = region_filled

In [118]:
df.head()

,date,category,value,product,sales,region,sales_fillna,value_fillna,value_fillna_median,region_filled
0,2026-01-01,A,50.0,Product3,491.0,North,491,50,50.0,North
1,2026-01-02,C,30.0,Product3,824.0,South,824,30,30.0,South
2,2026-01-03,B,18.0,Product2,857.0,South,857,18,18.0,South
3,2026-01-04,B,59.0,Product3,NaN,North,531,59,59.0,North
4,2026-01-05,B,89.0,Product2,908.0,West,908,89,89.0,West

### Assignment 12: Dropping Missing Values

Use `dropna()` to create:
1. `df_drop_rows`: all rows that contain at least one missing value are removed
2. `df_drop_cols`: all columns that contain at least one missing value are removed (`axis=1`)

Compare the `shape` of `df`, `df_drop_rows`, and `df_drop_cols`. What are the downsides of dropping data?

In [119]:
df_drop_rows = df.dropna()

In [120]:
df_drop_rows

,date,category,value,product,sales,region,sales_fillna,value_fillna,value_fillna_median,region_filled
0,2026-01-01,A,50.0,Product3,491.0,North,491,50,50.0,North
1,2026-01-02,C,30.0,Product3,824.0,South,824,30,30.0,South
2,2026-01-03,B,18.0,Product2,857.0,South,857,18,18.0,South
4,2026-01-05,B,89.0,Product2,908.0,West,908,89,89.0,West
5,2026-01-06,C,15.0,Product1,359.0,South,359,15,15.0,South
6,2026-01-07,A,87.0,Product3,315.0,East,315,87,87.0,East
7,2026-01-08,C,84.0,Product2,714.0,West,714,84,84.0,West
9,2026-01-10,A,66.0,Product2,225.0,South,225,66,66.0,South
10,2026-01-11,B,24.0,Product3,849.0,South,849,24,24.0,South
11,2026-01-12,C,78.0,Product1,279.0,South,279,78,78.0,South
12,2026-01-13,C,73.0,Product2,824.0,East,824,73,73.0,East
13,2026-01-14,C,41.0,Product1,106.0,South,106,41,41.0,South
14,2026-01-15,C,16.0,Product3,817.0,West,817,16,16.0,West
18,2026-01-19,C,71.0,Product2,524.0,North,524,71,71.0,North
19,2026-01-20,B,80.0,Product3,734.0,North,734,80,80.0,North
20,2026-01-21,B,78.0,Product3,349.0,West,349,78,78.0,West
21,2026-01-22,B,27.0,Product2,802.0,East,802,27,27.0,East
22,2026-01-23,A,42.0,Product1,600.0,North,600,42,42.0,North
24,2026-01-25,C,54.0,Product2,555.0,West,555,54,54.0,West
25,2026-01-26,B,13.0,Product3,611.0,West,611,13,13.0,West
26,2026-01-27,B,59.0,Product1,133.0,East,133,59,59.0,East
28,2026-01-29,B,76.0,Product3,320.0,West,320,76,76.0,West
29,2026-01-30,B,71.0,Product3,203.0,East,203,71,71.0,East

In [121]:
df_drop_cols = df.dropna(axis=1)

In [122]:
df_drop_cols

,date,category,product,region,sales_fillna,value_fillna,value_fillna_median,region_filled
0,2026-01-01,A,Product3,North,491,50,50.0,North
1,2026-01-02,C,Product3,South,824,30,30.0,South
2,2026-01-03,B,Product2,South,857,18,18.0,South
3,2026-01-04,B,Product3,North,531,59,59.0,North
4,2026-01-05,B,Product2,West,908,89,89.0,West
5,2026-01-06,C,Product1,South,359,15,15.0,South
6,2026-01-07,A,Product3,East,315,87,87.0,East
7,2026-01-08,C,Product2,West,714,84,84.0,West
8,2026-01-09,A,Product1,South,673,56,59.0,South
9,2026-01-10,A,Product2,South,225,66,66.0,South
10,2026-01-11,B,Product3,South,849,24,24.0,South
11,2026-01-12,C,Product1,South,279,78,78.0,South
12,2026-01-13,C,Product2,East,824,73,73.0,East
13,2026-01-14,C,Product1,South,106,41,41.0,South
14,2026-01-15,C,Product3,West,817,16,16.0,West
15,2026-01-16,C,Product2,North,531,97,97.0,North
16,2026-01-17,B,Product1,South,531,50,50.0,South
17,2026-01-18,A,Product1,East,531,90,90.0,East
18,2026-01-19,C,Product2,North,524,71,71.0,North
19,2026-01-20,B,Product3,North,734,80,80.0,North
20,2026-01-21,B,Product3,West,349,78,78.0,West
21,2026-01-22,B,Product2,East,802,27,27.0,East
22,2026-01-23,A,Product1,North,600,42,42.0,North
23,2026-01-24,C,Product3,North,513,56,59.0,North
24,2026-01-25,C,Product2,West,555,54,54.0,West
25,2026-01-26,B,Product3,West,611,13,13.0,West
26,2026-01-27,B,Product1,East,133,59,59.0,East
27,2026-01-28,C,Product1,East,225,56,59.0,East
28,2026-01-29,B,Product3,West,320,76,76.0,West
29,2026-01-30,B,Product3,East,203,71,71.0,East

## Part 3: Renaming Columns and Changing Data Types

### Assignment 13: Renaming a Column

Rename the `date` column to `sales_date` using `df.rename(columns={...})`, and store the result back in `df`. Print `df.head()` to confirm.

What happens if you pass a set like `{"date", "sales_date"}` instead of a dictionary with a colon? Why does pandas expect key-value pairs?

In [123]:
df = df.rename(columns={"date": "sales_date"})

In [124]:
df.head()

,sales_date,category,value,product,sales,region,sales_fillna,value_fillna,value_fillna_median,region_filled
0,2026-01-01,A,50.0,Product3,491.0,North,491,50,50.0,North
1,2026-01-02,C,30.0,Product3,824.0,South,824,30,30.0,South
2,2026-01-03,B,18.0,Product2,857.0,South,857,18,18.0,South
3,2026-01-04,B,59.0,Product3,NaN,North,531,59,59.0,North
4,2026-01-05,B,89.0,Product2,908.0,West,908,89,89.0,West

### Assignment 14: Changing Data Types: float to int

1. Create a new column `value_new` by converting the `value` column to `float` using `astype(float)`.
2. Now try to convert `value` straight to `int` using `astype(int)`. What error do you get and why?
3. Fix it: fill the missing values in `value` with the column mean first, then convert to `int`. Store the result in `value_new` and print `df.head()`.

In [125]:
value_new = df["value"].astype(float)

In [126]:
value_new

0     50.0
1     30.0
2     18.0
3     59.0
4     89.0
5     15.0
6     87.0
7     84.0
8      NaN
9     66.0
10    24.0
11    78.0
12    73.0
13    41.0
14    16.0
15    97.0
16    50.0
17    90.0
18    71.0
19    80.0
20    78.0
21    27.0
22    42.0
23     NaN
24    54.0
25    13.0
26    59.0
27     NaN
28    76.0
29    71.0
Name: value, dtype: float64

In [127]:
df["value_new"] = value_new

In [128]:
# df["value"].astype(int)

In [129]:
df["value"].fillna(df["value"].mean()).astype(int)

0     50
1     30
2     18
3     59
4     89
5     15
6     87
7     84
8     56
9     66
10    24
11    78
12    73
13    41
14    16
15    97
16    50
17    90
18    71
19    80
20    78
21    27
22    42
23    56
24    54
25    13
26    59
27    56
28    76
29    71
Name: value, dtype: int64

### Assignment 15: Converting a Column to Datetime

The lecture mentioned that `date` (now `sales_date`) is stored as a string.
1. Convert `sales_date` to a proper datetime using `pd.to_datetime`.
2. Check `df.dtypes` to confirm the change.
3. Create a new column `month` by extracting the month number from `sales_date` (hint: `.dt.month`).

In [130]:
df["sales_date"] = pd.to_datetime(df["sales_date"])

In [131]:
month = df["sales_date"].dt.month

In [132]:
df["month"] = month

In [133]:
df.head()

,sales_date,category,value,product,sales,region,sales_fillna,value_fillna,value_fillna_median,region_filled,value_new,month
0,2026-01-01,A,50.0,Product3,491.0,North,491,50,50.0,North,50.0,1
1,2026-01-02,C,30.0,Product3,824.0,South,824,30,30.0,South,30.0,1
2,2026-01-03,B,18.0,Product2,857.0,South,857,18,18.0,South,18.0,1
3,2026-01-04,B,59.0,Product3,NaN,North,531,59,59.0,North,59.0,1
4,2026-01-05,B,89.0,Product2,908.0,West,908,89,89.0,West,89.0,1

## Part 4: Applying Functions to Columns

### Assignment 16: Apply with a Lambda

Create a new column `value_double` by applying a lambda function to `value_new` that multiplies each value by 2, using `df["value_new"].apply(lambda x: ...)`. Print `df.head()` and compare `value_new` with `value_double`.

In [134]:
value_double = df["value_new"].apply(lambda val: val * 2)

In [135]:
df["value_double"] = value_double

In [136]:
df.head()

,sales_date,category,value,product,sales,region,sales_fillna,value_fillna,value_fillna_median,region_filled,value_new,month,value_double
0,2026-01-01,A,50.0,Product3,491.0,North,491,50,50.0,North,50.0,1,100.0
1,2026-01-02,C,30.0,Product3,824.0,South,824,30,30.0,South,30.0,1,60.0
2,2026-01-03,B,18.0,Product2,857.0,South,857,18,18.0,South,18.0,1,36.0
3,2026-01-04,B,59.0,Product3,NaN,North,531,59,59.0,North,59.0,1,118.0
4,2026-01-05,B,89.0,Product2,908.0,West,908,89,89.0,West,89.0,1,178.0

### Assignment 17: Apply with a Custom Function

Write a regular function `add_tax(price)` that increases a number by 10 percent. Apply it to the `sales_fillna` column using `apply` (pass the function name without parentheses) and store the result in `sales_with_tax`.

Then write another function `sales_level(x)` that returns `"High"` if `x >= 600`, otherwise `"Low"`, and apply it to create a `sales_level` column. Count how many rows are `"High"` using `value_counts()`.

In [137]:
def add_tax(price: float) -> float:
    return price * 1.1

In [138]:
df["sales_with_tax"] = df["sales_fillna"].apply(add_tax)

In [139]:
def sales_level(x: float) -> str:
    return "High" if x >= 600 else "Low"

In [140]:
df["sales_level"] = df["sales_with_tax"].apply(sales_level)

In [141]:
df["sales_level"].value_counts()

sales_level
Low     17
High    13
Name: count, dtype: int64

## Part 5: Aggregating and Grouping Data

### Assignment 18: Group by a Single Column

Group `df` by `product` and calculate the mean of `value`. Store the result in `grouped_mean` and print it. What type of object is `grouped_mean` and what is its index?

In [142]:
grouped_mean = df.groupby("product")["value"].mean()

In [143]:
grouped_mean

product
Product1    53.571429
Product2    64.333333
Product3    53.090909
Name: value, dtype: float64

### Assignment 19: Group by Multiple Columns

Group `df` by both `product` and `region` (pass a list of the columns to `groupby`) and calculate the **sum** of `value`. Store it in `grouped_sum` and print it.
1. How many index levels does the result have?
2. Repeat the same grouping, but calculate the **mean** instead of the sum.

In [144]:
df.groupby(["product", "region"])["value"].sum()

product   region
Product1  East      149.0
          North      42.0
          South     184.0
Product2  East      100.0
          North     168.0
          South      84.0
          West      227.0
Product3  East      158.0
          North     189.0
          South      54.0
          West      183.0
Name: value, dtype: float64

In [145]:
df.groupby(["product", "region"])["value"].mean()

product   region
Product1  East      74.500000
          North     42.000000
          South     46.000000
Product2  East      50.000000
          North     84.000000
          South     42.000000
          West      75.666667
Product3  East      79.000000
          North     63.000000
          South     27.000000
          West      45.750000
Name: value, dtype: float64

### Assignment 20: Multiple Aggregate Functions

Group `df` by `region` and calculate the `mean`, `sum`, and `count` of the `value` column in one step using `.agg(["mean", "sum", "count"])`. Store the result in `grouped_agg` and print it.

Which region has the highest total? Which has the most records?

In [146]:
df.groupby("region")["value"].agg(["mean", "sum", "count"])

             mean    sum  count
region
East    67.833333  407.0      6
North   66.500000  399.0      6
South   40.250000  322.0      8
West    58.571429  410.0      7

### Assignment 21: Different Aggregation per Column

Group `df` by `product` and compute, in a single `agg` call, both of the following:
- the **sum** of `value_new`
- the **mean** and **max** of `sales_fillna`

(Hint: pass a dictionary mapping column names to the function(s) to apply.)

In [147]:
df.groupby(["product", "region"]).agg({"value_new": "sum", "sales_fillna": ["mean", "max", "median"]})

                value_new sales_fillna
                      sum         mean  max median
product  region
Product1 East       149.0   296.333333  531  225.0
         North       42.0   600.000000  600  600.0
         South      184.0   389.600000  673  359.0
Product2 East       100.0   813.000000  824  813.0
         North      168.0   527.500000  531  527.5
         South       84.0   541.000000  857  541.0
         West       227.0   725.666667  908  714.0
Product3 East       158.0   259.000000  315  259.0
         North      189.0   567.250000  734  522.0
         South       54.0   836.500000  849  836.5
         West       183.0   524.250000  817  480.0

### Assignment 22: SQL Comparison

Everything you did in Part 5 can also be written in SQL. Write (as comments or a markdown cell) the equivalent SQL query for each of these:
1. Mean of `value` per `product`
2. Sum of `value` per `product` and `region`
3. Mean, sum, and count of `value` per `region`

Which pandas method plays the role of `GROUP BY`? Which plays the role of `SELECT AVG(...)`?

In [148]:
"""
SELECT product, AVG(value) AS mean_value
FROM table_name
GROUP BY product;
"""

'\nSELECT product, AVG(value) AS mean_value\nFROM table_name\nGROUP BY product;\n'

In [149]:
"""
SELECT product, region, SUM(value) as total_value
FROM table_name
GROUP BY product, region;
"""

'\nSELECT product, region, SUM(value) as total_value\nFROM table_name\nGROUP BY product, region;\n'

In [150]:
"""
SELECT region,
       AVG(value)   AS mean_value,
       SUM(value)   AS total_value,
       COUNT(value) AS count_value
FROM table_name
GROUP BY region;
"""

'\nSELECT region,\n       AVG(value) AS mean_value,\n       SUM(value) AS total_value,\n       COUNT(value) AS count_value\nFROM table_name\nGROUP BY region;\n'

## Part 6: Merging and Joining DataFrames

### Assignment 23: Create Two DataFrames

Create the two DataFrames below and print both. Which keys appear in both? Which appear only in `df1`? Which appear only in `df2`?

In [151]:
df1 = pd.DataFrame({"key": ["A", "B", "C"], "value1": [1, 2, 3]})
df2 = pd.DataFrame({"key": ["A", "B", "D"], "value2": [4, 5, 6]})

In [152]:
df1

  key  value1
0   A       1
1   B       2
2   C       3

In [153]:
df2

  key  value2
0   A       4
1   B       5
2   D       6

### Assignment 24: Inner Join

Merge `df1` and `df2` on the `key` column using an **inner** join: `pd.merge(df1, df2, on="key", how="inner")`. Which rows are in the result and why are `C` and `D` missing?

In [156]:
pd.merge(df1, df2, on="key", how="inner")

  key  value1  value2
0   A       1       4
1   B       2       5

### Assignment 25: Outer Join

Merge `df1` and `df2` on `key` with `how="outer"`. Where do `NaN` values appear and why?

In [160]:
pd.merge(df1, df2, on="key", how="outer")

  key  value1  value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

### Assignment 26: Left Join

Merge `df1` and `df2` on `key` with `how="left"`. Which DataFrame's keys are all kept? What value is given to `value2` for key `C`?

In [161]:
pd.merge(df1, df2, on="key", how="left")

  key  value1  value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

### Assignment 27: Right Join

Merge `df1` and `df2` on `key` with `how="right"`. Which DataFrame's keys are all kept now? What value is given to `value1` for key `D`?

In [162]:
pd.merge(df1, df2, on="key", how="right")

  key  value1  value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

### Assignment 28: Merge with Different Key Names

Create two new DataFrames:
- `employees` with columns `emp_id` (1, 2, 3, 4) and `name`
- `salaries` with columns `id` (2, 3, 4, 5) and `salary`

Merge them with `left_on="emp_id"` and `right_on="id"` using a left join. Then drop the redundant `id` column from the result.

In [166]:
employees = pd.DataFrame({
    "emp_id": [1, 2, 3, 4],
})

salaries = pd.DataFrame({
    "salaries": [2, 3, 4, 5]
})

In [168]:
pd.merge(employees, salaries, left_on="emp_id", right_on="salaries")

   emp_id  salaries
0       2         2
1       3         3
2       4         4

## Part 7: Practice on the Online Sales Data

### Assignment 29: Load the Sales Dataset

Load `Online Sales Data.csv` (the file already in this folder) into a DataFrame named `sales`. Use `head()`, `info()`, and `describe()` to explore it. Check whether it has any missing values with `isnull().sum()`.

In [169]:
sales_data = pd.read_csv("Online Sales Data.csv")

In [170]:
sales_data.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2026-01-01,Home Appliances,Blender,9,69.99,629.91,Africa,PayPal
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal
2,10003,2026-01-02,Clothing,Yoga Pants,5,39.99,199.95,Asia,PayPal
3,10004,2026-01-05,Beauty Products,Perfume,9,74.99,674.91,North America,Credit Card
4,10005,2026-01-05,Beauty Products,Perfume,5,74.99,374.95,North America,Gift Card

In [171]:
sales_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    500 non-null    int64
 1   Date              500 non-null    str
 2   Product Category  500 non-null    str
 3   Product Name      500 non-null    str
 4   Units Sold        500 non-null    int64
 5   Unit Price        500 non-null    float64
 6   Total Revenue     500 non-null    float64
 7   Region            500 non-null    str
 8   Payment Method    500 non-null    str
dtypes: float64(2), int64(2), str(5)
memory usage: 35.3 KB

In [172]:
sales_data.describe()

       Transaction ID  Units Sold  Unit Price  Total Revenue
count      500.000000  500.000000  500.000000     500.000000
mean     10250.500000    5.472000   52.026000     290.243280
std        144.481833    2.753248   38.421754     268.294693
min      10001.000000    1.000000   11.990000      11.990000
25%      10125.750000    3.000000   21.990000      95.677500
50%      10250.500000    6.000000   44.990000     199.950000
75%      10375.250000    8.000000   71.240000     401.212500
max      10500.000000   10.000000  199.990000    1799.910000

In [175]:
sales_data["Date"] = pd.to_datetime(sales_data["Date"])

In [176]:
sales_data.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2026-01-01,Home Appliances,Blender,9,69.99,629.91,Africa,PayPal
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal
2,10003,2026-01-02,Clothing,Yoga Pants,5,39.99,199.95,Asia,PayPal
3,10004,2026-01-05,Beauty Products,Perfume,9,74.99,674.91,North America,Credit Card
4,10005,2026-01-05,Beauty Products,Perfume,5,74.99,374.95,North America,Gift Card

In [179]:
sales_data.isnull()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False

### Assignment 30: Average Sales by Product

Calculate the average `Total Revenue` for each `Product Name`. Sort the result from highest to lowest average and print the top 5 products.

In [182]:
sales_data.groupby("Product Name")["Total Revenue"].mean(skipna=True).sort_values(ascending=False)

Product Name
Smartwatch               945.407273
Vacuum Cleaner           769.948667
Tennis Racket            662.433750
Running Shoes            557.080952
Air Fryer                539.940000
Wireless Earbuds         479.940000
Dumbbell Set             451.372143
Denim Jacket             433.266667
Perfume                  392.594706
Blender                  369.947143
Deep Learning Basics     327.740400
Coffee Maker             308.520000
Bluetooth Speaker        264.652941
Yoga Pants               251.048333
Data Science Handbook    233.948000
Python Crash Course      225.844545
Hoodie                   222.582105
Electric Kettle          192.445000
Lipstick Set             175.441500
USB-C Charger            133.280000
Face Moisturizer         130.276667
Yoga Mat                 121.286667
Atomic Habits            102.939412
Resistance Bands         102.620000
Cotton T-Shirt            99.950000
Water Bottle              93.593571
Sunscreen SPF 50          83.503333
Smartphone Case           69.953333
The Alchemist             58.455000
Shampoo                   53.955000
Name: Total Revenue, dtype: float64

### Assignment 31: Group by Category and Region

Using the `sales` DataFrame:
1. Calculate the total `Total Revenue` for each `Product Category` and `Region` combination.
2. Which category/region combination generates the most revenue?
3. Calculate the sum, mean, and count of `Units Sold` for every `Payment Method`.

In [185]:
sales_data.groupby(["Product Category", "Region"])["Total Revenue"].sum()

Product Category  Region
Beauty Products   Africa           1560.26
                  Asia             2284.22
                  Europe           2119.47
                  North America    2682.20
                  Oceania          3672.00
                  South America    2185.28
Books             Africa           2137.30
                  Asia             2795.20
                  Europe           2530.39
                  North America    2685.36
                  Oceania          3302.25
                  South America    2837.22
Clothing          Africa           4649.23
                  Asia             5749.02
                  Europe           4834.15
                  North America    3924.35
                  Oceania          7043.75
                  South America    4144.33
Electronics       Africa           3544.32
                  Asia             2734.34
                  Europe           3229.39
                  North America    3354.10
                  Oceania          8024.40
                  South America    5639.23
Home Appliances   Africa           7169.14
                  Asia             5889.24
                  Europe           6689.09
                  North America    1434.74
                  Oceania          5944.29
                  South America    6764.29
Sports            Africa           4357.27
                  Asia             3002.37
                  Europe           3514.20
                  North America    6657.94
                  Oceania          2558.17
                  South America    3479.14
Name: Total Revenue, dtype: float64

In [184]:
sales_data.groupby(["Product Category", "Region"])["Total Revenue"].sum().sort_values(ascending=False)

Product Category  Region
Electronics       Oceania          8024.40
Home Appliances   Africa           7169.14
Clothing          Oceania          7043.75
Home Appliances   South America    6764.29
                  Europe           6689.09
Sports            North America    6657.94
Home Appliances   Oceania          5944.29
                  Asia             5889.24
Clothing          Asia             5749.02
Electronics       South America    5639.23
Clothing          Europe           4834.15
                  Africa           4649.23
Sports            Africa           4357.27
Clothing          South America    4144.33
                  North America    3924.35
Beauty Products   Oceania          3672.00
Electronics       Africa           3544.32
Sports            Europe           3514.20
                  South America    3479.14
Electronics       North America    3354.10
Books             Oceania          3302.25
Electronics       Europe           3229.39
Sports            Asia             3002.37
Books             South America    2837.22
                  Asia             2795.20
Electronics       Asia             2734.34
Books             North America    2685.36
Beauty Products   North America    2682.20
Sports            Oceania          2558.17
Books             Europe           2530.39
Beauty Products   Asia             2284.22
                  South America    2185.28
Books             Africa           2137.30
Beauty Products   Europe           2119.47
                  Africa           1560.26
Home Appliances   North America    1434.74
Name: Total Revenue, dtype: float64

In [192]:
sales_data.groupby("Payment Method")["Units Sold"].agg(units_sold="sum", average="mean", total="count")

                units_sold   average  total
Payment Method
Bank Transfer          588  5.345455    110
Credit Card            504  5.793103     87
Debit Card             486  5.115789     95
Gift Card              634  5.610619    113
PayPal                 524  5.515789     95

### Assignment 32: Merge Practice with the Sales Data

1. Create a DataFrame `region_manager` with columns `Region` and `Manager` for every unique region in `sales` (invent the manager names).
2. Merge it into `sales` on `Region`.
3. Calculate the total `Total Revenue` handled by each manager.

In [195]:
sales_region = sales_data["Region"].unique()
sales_region

<StringArray>
['Africa', 'Oceania', 'Asia', 'North America', 'Europe', 'South America']
Length: 6, dtype: str

In [201]:
sales_manager =  np.array(["Aarav Mehta", "Priya Nair", "Rohan Kulkarni", "Sneha Iyer", "Vikram Singh", "ACBC"])
sales_manager

array(['Aarav Mehta', 'Priya Nair', 'Rohan Kulkarni', 'Sneha Iyer',
       'Vikram Singh', 'ACBC'], dtype='<U14')

In [210]:
region_manager = pd.DataFrame(
    {
        "Region": sales_region,
        "Manager": sales_manager,
    }
)

In [211]:
sales_data.merge(region_manager, on="Region", how="left")

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Manager
0,10001,2026-01-01,Home Appliances,Blender,9,69.99,629.91,Africa,PayPal,Aarav Mehta
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal,Priya Nair
2,10003,2026-01-02,Clothing,Yoga Pants,5,39.99,199.95,Asia,PayPal,Rohan Kulkarni
3,10004,2026-01-05,Beauty Products,Perfume,9,74.99,674.91,North America,Credit Card,Sneha Iyer
4,10005,2026-01-05,Beauty Products,Perfume,5,74.99,374.95,North America,Gift Card,Sneha Iyer
...,...,...,...,...,...,...,...,...,...,...
495,10496,2026-09-29,Clothing,Hoodie,9,44.99,404.91,Asia,Gift Card,Rohan Kulkarni
496,10497,2026-09-29,Home Appliances,Blender,6,69.99,419.94,Africa,PayPal,Aarav Mehta
497,10498,2026-09-29,Sports,Yoga Mat,2,25.99,51.98,Europe,Gift Card,Vikram Singh
498,10499,2026-09-29,Electronics,Smartwatch,3,199.99,599.97,Asia,Gift Card,Rohan Kulkarni
499,10500,2026-09-29,Home Appliances,Coffee Maker,1,59.99,59.99,Europe,Debit Card,Vikram Singh

### Assignment 33: Mini EDA Challenge

Combine everything you learned in this lesson:
1. Convert `Date` to datetime and create a `Month` column.
2. Group by `Month` and calculate the total `Total Revenue`.
3. Create a column `Revenue Level` that is `"High"` when `Total Revenue` is above the overall mean, otherwise `"Low"` (use `apply` or a vectorised comparison).
4. Rename `Total Revenue` to `Revenue` and `Units Sold` to `Units`.
5. In a markdown cell, write 3-4 sentences about the insights you found.

In [215]:
sales_data["Month"] = sales_data["Date"].dt.month

In [216]:
sales_data.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Month
0,10001,2026-01-01,Home Appliances,Blender,9,69.99,629.91,Africa,PayPal,1
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal,1
2,10003,2026-01-02,Clothing,Yoga Pants,5,39.99,199.95,Asia,PayPal,1
3,10004,2026-01-05,Beauty Products,Perfume,9,74.99,674.91,North America,Credit Card,1
4,10005,2026-01-05,Beauty Products,Perfume,5,74.99,374.95,North America,Gift Card,1

In [217]:
sales_data.groupby(["Month", "Total Revenue"]).head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Month
0,10001,2026-01-01,Home Appliances,Blender,9,69.99,629.91,Africa,PayPal,1
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal,1
2,10003,2026-01-02,Clothing,Yoga Pants,5,39.99,199.95,Asia,PayPal,1
3,10004,2026-01-05,Beauty Products,Perfume,9,74.99,674.91,North America,Credit Card,1
4,10005,2026-01-05,Beauty Products,Perfume,5,74.99,374.95,North America,Gift Card,1
...,...,...,...,...,...,...,...,...,...,...
495,10496,2026-09-29,Clothing,Hoodie,9,44.99,404.91,Asia,Gift Card,9
496,10497,2026-09-29,Home Appliances,Blender,6,69.99,419.94,Africa,PayPal,9
497,10498,2026-09-29,Sports,Yoga Mat,2,25.99,51.98,Europe,Gift Card,9
498,10499,2026-09-29,Electronics,Smartwatch,3,199.99,599.97,Asia,Gift Card,9
499,10500,2026-09-29,Home Appliances,Coffee Maker,1,59.99,59.99,Europe,Debit Card,9

In [219]:
sales_data["Revenue Level"] = sales_data["Total Revenue"].apply(lambda x: sales_level(x))
sales_data["Revenue Level"].head()

0    High
1     Low
2     Low
3    High
4     Low
Name: Revenue Level, dtype: str

In [220]:
sales_data.rename({"Total Revenue": "Revenue", "Units Sold": "Units"}, axis=1, inplace=True)

In [221]:
sales_data.columns

Index(['Transaction ID', 'Date', 'Product Category', 'Product Name', 'Units',
       'Unit Price', 'Revenue', 'Region', 'Payment Method', 'Month',
       'Revenue Level'],
      dtype='str')

In [223]:
sales_data.head()

,Transaction ID,Date,Product Category,Product Name,Units,Unit Price,Revenue,Region,Payment Method,Month,Revenue Level
0,10001,2026-01-01,Home Appliances,Blender,9,69.99,629.91,Africa,PayPal,1,High
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal,1,Low
2,10003,2026-01-02,Clothing,Yoga Pants,5,39.99,199.95,Asia,PayPal,1,Low
3,10004,2026-01-05,Beauty Products,Perfume,9,74.99,674.91,North America,Credit Card,1,High
4,10005,2026-01-05,Beauty Products,Perfume,5,74.99,374.95,North America,Gift Card,1,Low