# Module: Pandas Assignments
## Lesson: Pandas DataFrame and Series
### Assignment 0: Setup

Make sure `pandas` and `numpy` are listed in your `requirements.txt` and installed in your activated virtual environment (`pip install -r requirements.txt`). Import both libraries using the standard aliases `pd` and `np`, and print the version of pandas you are using.

In [1]:
import pandas as pd
import numpy as np

### Assignment 1: Series from a List

Create a Pandas Series from the list `[1, 2, 3, 4, 5]`. Print the Series and print its type. What are the default index values?

In [2]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

### Assignment 2: Series from a Dictionary

Create a Series from the dictionary `{"a": 1, "b": 2, "c": 3}`. Print it and explain (in a markdown cell or a comment) what happened to the dictionary keys.

In [3]:
pd.Series({"a": 1, "b": 2, "c": 3})

a    1
b    2
c    3
dtype: int64

### Assignment 3: Series with a Custom Index

Create a Series from the data `[10, 20, 30]` with the custom index `["a", "b", "c"]` by passing the `index` parameter. Then access the value at index `"b"`.

In [7]:
data = np.array([10, 20, 30])
index = np.array(["a", "b", "c"])
# pd.Series(dict(zip(index, data)))
pd.Series(data, index)

a    10
b    20
c    30
dtype: int64

### Assignment 4: Series from a NumPy Array

Create a one-dimensional NumPy array of the numbers 1 to 5 and convert it into a Pandas Series. Multiply every element of the Series by 10 and print the result.

In [17]:
one_dim_arr = np.array([1, 2, 3, 4, 5])

In [18]:
pd.Series(one_dim_arr)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [19]:
pd.Series(one_dim_arr * 10)

0    10
1    20
2    30
3    40
4    50
dtype: int64

### Assignment 5: DataFrame from a Dictionary of Lists

Create a DataFrame from a dictionary where the keys are `name`, `age`, and `city` and each value is a list of three items (e.g. Krish / John / Jack, 25 / 30 / 45, Bangalore / New York / Florida). Print the DataFrame and its type.

In [29]:
import csv

with open("Online Sales Data.csv", "r", encoding="utf-8") as file:
    data = csv.reader(file)
    column = next(data)
    data_frame = pd.DataFrame(data, columns=column)

    print(data_frame)

    Transaction ID        Date Product Category   Product Name Units Sold  \
0            10001  2026-01-01  Home Appliances        Blender          9
1            10002  2026-01-02            Books  Atomic Habits          8
2            10003  2026-01-02         Clothing     Yoga Pants          5
3            10004  2026-01-05  Beauty Products        Perfume          9
4            10005  2026-01-05  Beauty Products        Perfume          5
..             ...         ...              ...            ...        ...
495          10496  2026-09-29         Clothing         Hoodie          9
496          10497  2026-09-29  Home Appliances        Blender          6
497          10498  2026-09-29           Sports       Yoga Mat          2
498          10499  2026-09-29      Electronics     Smartwatch          3
499          10500  2026-09-29  Home Appliances   Coffee Maker          1

    Unit Price Total Revenue         Region Payment Method
0        69.99        629.91         Africa         PayPal
1        16.99        135.92        Oceania         PayPal
2        39.99        199.95           Asia         PayPal
3        74.99        674.91  North America    Credit Card
4        74.99        374.95  North America      Gift Card
..         ...           ...            ...            ...
495      44.99        404.91           Asia      Gift Card
496      69.99        419.94         Africa         PayPal
497      25.99         51.98         Europe      Gift Card
498     199.99        599.97           Asia      Gift Card
499      59.99         59.99         Europe     Debit Card

[500 rows x 9 columns]

In [30]:
np.array(data_frame)

array([['10001', '2026-01-01', 'Home Appliances', ..., '629.91',
        'Africa', 'PayPal'],
       ['10002', '2026-01-02', 'Books', ..., '135.92', 'Oceania',
        'PayPal'],
       ['10003', '2026-01-02', 'Clothing', ..., '199.95', 'Asia',
        'PayPal'],
       ...,
       ['10498', '2026-09-29', 'Sports', ..., '51.98', 'Europe',
        'Gift Card'],
       ['10499', '2026-09-29', 'Electronics', ..., '599.97', 'Asia',
        'Gift Card'],
       ['10500', '2026-09-29', 'Home Appliances', ..., '59.99', 'Europe',
        'Debit Card']], shape=(500, 9), dtype=object)

In [33]:
data_frame = pd.read_csv("Online Sales Data.csv")

In [34]:
data_frame.head(10)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2026-01-01,Home Appliances,Blender,9,69.99,629.91,Africa,PayPal
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal
2,10003,2026-01-02,Clothing,Yoga Pants,5,39.99,199.95,Asia,PayPal
3,10004,2026-01-05,Beauty Products,Perfume,9,74.99,674.91,North America,Credit Card
4,10005,2026-01-05,Beauty Products,Perfume,5,74.99,374.95,North America,Gift Card
5,10006,2026-01-05,Beauty Products,Perfume,1,74.99,74.99,Oceania,Debit Card
6,10007,2026-01-06,Beauty Products,Shampoo,9,11.99,107.91,Oceania,Credit Card
7,10008,2026-01-06,Clothing,Yoga Pants,5,39.99,199.95,Africa,Debit Card
8,10009,2026-01-06,Clothing,Yoga Pants,10,39.99,399.90,Asia,PayPal
9,10010,2026-01-06,Clothing,Hoodie,2,44.99,89.98,North America,PayPal

0            Blender
1      Atomic Habits
2         Yoga Pants
3            Perfume
4            Perfume
           ...
495           Hoodie
496          Blender
497         Yoga Mat
498       Smartwatch
499     Coffee Maker
Name: Product Name, Length: 500, dtype: str

In [38]:
data_frame.loc[0]

Transaction ID                10001
Date                     2026-01-01
Product Category    Home Appliances
Product Name                Blender
Units Sold                        9
Unit Price                    69.99
Total Revenue                629.91
Region                       Africa
Payment Method               PayPal
Name: 0, dtype: object

### Assignment 6: DataFrame to NumPy Array

Convert the DataFrame from Assignment 5 into a NumPy array using `np.array(df)`. Print the array and describe what happened to the index and the column names.

In [39]:
np.array(data_frame)

array([[10001, '2026-01-01', 'Home Appliances', ..., 629.91, 'Africa',
        'PayPal'],
       [10002, '2026-01-02', 'Books', ..., 135.92, 'Oceania', 'PayPal'],
       [10003, '2026-01-02', 'Clothing', ..., 199.95, 'Asia', 'PayPal'],
       ...,
       [10498, '2026-09-29', 'Sports', ..., 51.98, 'Europe', 'Gift Card'],
       [10499, '2026-09-29', 'Electronics', ..., 599.97, 'Asia',
        'Gift Card'],
       [10500, '2026-09-29', 'Home Appliances', ..., 59.99, 'Europe',
        'Debit Card']], shape=(500, 9), dtype=object)

### Assignment 7: DataFrame from a List of Dictionaries

Create a DataFrame from a list of dictionaries, where each dictionary is one row with the keys `name`, `age`, and `city`. Use at least four rows with different values. Print the DataFrame.

In [ ]:
data = [
    {"Name": "John", "age": 32, "City": "Beijing"},
    {"Name": "Rex", "age": 33, "City": "Ohio"},
    {"Name": "Raj", "age": 34, "City": "Mumbai"},
]

pd.DataFrame(data)

### Assignment 8: Reading a CSV File

Create a small sales dataset as a DataFrame with the columns `transaction_id`, `product`, `units_sold`, `unit_price`, and `total_revenue` (at least 8 rows, where `total_revenue = units_sold * unit_price`). Save it to a file named `sales_data.csv` using `to_csv(..., index=False)`, then read it back using `pd.read_csv`.

### Assignment 9: Viewing the Top and Bottom Rows

Using the DataFrame read from `sales_data.csv`, display:
1. The first 5 rows using `head()`
2. The last 5 rows using `tail()`
3. The first 3 rows using `head(3)`

In [40]:
data_frame.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2026-01-01,Home Appliances,Blender,9,69.99,629.91,Africa,PayPal
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal
2,10003,2026-01-02,Clothing,Yoga Pants,5,39.99,199.95,Asia,PayPal
3,10004,2026-01-05,Beauty Products,Perfume,9,74.99,674.91,North America,Credit Card
4,10005,2026-01-05,Beauty Products,Perfume,5,74.99,374.95,North America,Gift Card

In [41]:
data_frame.tail()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
495,10496,2026-09-29,Clothing,Hoodie,9,44.99,404.91,Asia,Gift Card
496,10497,2026-09-29,Home Appliances,Blender,6,69.99,419.94,Africa,PayPal
497,10498,2026-09-29,Sports,Yoga Mat,2,25.99,51.98,Europe,Gift Card
498,10499,2026-09-29,Electronics,Smartwatch,3,199.99,599.97,Asia,Gift Card
499,10500,2026-09-29,Home Appliances,Coffee Maker,1,59.99,59.99,Europe,Debit Card

In [42]:
data_frame.head(3)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2026-01-01,Home Appliances,Blender,9,69.99,629.91,Africa,PayPal
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal
2,10003,2026-01-02,Clothing,Yoga Pants,5,39.99,199.95,Asia,PayPal

### Assignment 10: Accessing a Column

Using the DataFrame from Assignment 5, select the `name` column using `df["name"]`. Print the result and its type. Why is it a Series and not a DataFrame?

In [45]:
df = data_frame["Product Name"]
print(df)

0            Blender
1      Atomic Habits
2         Yoga Pants
3            Perfume
4            Perfume
           ...
495           Hoodie
496          Blender
497         Yoga Mat
498       Smartwatch
499     Coffee Maker
Name: Product Name, Length: 500, dtype: str

In [46]:
type(df)

pandas.Series

### Assignment 11: Accessing Multiple Columns

Select the `name` and `city` columns together as a new DataFrame. Print the result and its type. (Hint: pass a list of column names.)

In [50]:
df = data_frame[["Product Name", "Region"]].head()
print(df)

    Product Name         Region
0        Blender         Africa
1  Atomic Habits        Oceania
2     Yoga Pants           Asia
3        Perfume  North America
4        Perfume  North America

In [51]:
type(df)

pandas.DataFrame

### Assignment 12: Accessing Rows with `loc`

Using `df.loc`, select:
1. The row with index label `0`
2. The rows with index labels `0` through `1`
3. The `age` value of the row with index label `2`

Explain what `loc` is label-based on.

In [63]:
data_frame.loc[0]

Transaction ID                10001
Date                     2026-01-01
Product Category    Home Appliances
Product Name                Blender
Units Sold                        9
Unit Price                    69.99
Total Revenue                629.91
Region                       Africa
Payment Method               PayPal
Name: 0, dtype: object

In [59]:
data_frame.loc[0:1]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2026-01-01,Home Appliances,Blender,9,69.99,629.91,Africa,PayPal
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal

In [73]:
data_frame.loc[0:8, ["Date", "Product Category", "Total Revenue", "Payment Method"]]

         Date Product Category  Total Revenue Payment Method
0  2026-01-01  Home Appliances         629.91         PayPal
1  2026-01-02            Books         135.92         PayPal
2  2026-01-02         Clothing         199.95         PayPal
3  2026-01-05  Beauty Products         674.91    Credit Card
4  2026-01-05  Beauty Products         374.95      Gift Card
5  2026-01-05  Beauty Products          74.99     Debit Card
6  2026-01-06  Beauty Products         107.91    Credit Card
7  2026-01-06         Clothing         199.95     Debit Card
8  2026-01-06         Clothing         399.90         PayPal

In [75]:
filter_data = data_frame.loc[
    (data_frame["Units Sold"] > 5)
    & (data_frame["Total Revenue"] < 150)
    & (data_frame["Payment Method"].isin(["Credit Card", "PayPal", "Wire Transfer"]))
]

In [77]:
filter_data.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal
6,10007,2026-01-06,Beauty Products,Shampoo,9,11.99,107.91,Oceania,Credit Card
17,10018,2026-01-14,Beauty Products,Sunscreen SPF 50,9,15.99,143.91,Africa,PayPal
19,10020,2026-01-15,Sports,Water Bottle,6,18.99,113.94,South America,PayPal
34,10035,2026-01-22,Sports,Resistance Bands,6,21.99,131.94,North America,Credit Card

In [78]:
filter_data.sort_values(["Product Category", "Units Sold", "Region", "Payment Method"])

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
101,10102,2026-02-22,Beauty Products,Shampoo,6,11.99,71.94,North America,PayPal
217,10218,2026-05-04,Beauty Products,Face Moisturizer,6,22.99,137.94,South America,Credit Card
102,10103,2026-02-22,Beauty Products,Sunscreen SPF 50,7,15.99,111.93,North America,Credit Card
467,10468,2026-09-14,Beauty Products,Sunscreen SPF 50,7,15.99,111.93,North America,Credit Card
17,10018,2026-01-14,Beauty Products,Sunscreen SPF 50,9,15.99,143.91,Africa,PayPal
6,10007,2026-01-06,Beauty Products,Shampoo,9,11.99,107.91,Oceania,Credit Card
478,10479,2026-09-20,Books,The Alchemist,6,12.99,77.94,Africa,Credit Card
143,10144,2026-03-16,Books,The Alchemist,6,12.99,77.94,Asia,Credit Card
141,10142,2026-03-15,Books,Atomic Habits,6,16.99,101.94,Asia,PayPal
151,10152,2026-03-22,Books,The Alchemist,6,12.99,77.94,Asia,PayPal
265,10266,2026-06-02,Books,Atomic Habits,7,16.99,118.93,South America,Credit Card
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal
302,10303,2026-06-18,Electronics,Smartphone Case,7,14.99,104.93,Asia,Credit Card
486,10487,2026-09-27,Electronics,Smartphone Case,7,14.99,104.93,North America,Credit Card
91,10092,2026-02-17,Sports,Resistance Bands,6,21.99,131.94,Europe,PayPal
34,10035,2026-01-22,Sports,Resistance Bands,6,21.99,131.94,North America,Credit Card
326,10327,2026-07-04,Sports,Water Bottle,6,18.99,113.94,North America,Credit Card
177,10178,2026-04-09,Sports,Resistance Bands,6,21.99,131.94,Oceania,Credit Card
228,10229,2026-05-10,Sports,Water Bottle,6,18.99,113.94,Oceania,Credit Card
376,10377,2026-07-26,Sports,Water Bottle,6,18.99,113.94,Oceania,PayPal
19,10020,2026-01-15,Sports,Water Bottle,6,18.99,113.94,South America,PayPal

In [66]:
data_frame.iloc[0, 1]

'2026-01-01'

### Assignment 13: Accessing Rows and Columns with `iloc`

Using `df.iloc`, select:
1. The first row
2. The element at row `0`, column `0`
3. The element at row `0`, column `2`
4. The element at row `2`, column `2`

Explain how `iloc` differs from `loc`.

In [ ]:
data_frame.iloc[0]

In [68]:
data_frame.iloc[0, 0]

np.int64(10001)

In [ ]:
data_frame.iloc[0, 2]

'Home Appliances'

In [70]:
data_frame.iloc[2, 2]

'Clothing'

### Assignment 14: Accessing a Single Value with `at` and `iat`

Use `df.at` to get the `age` of the row with index `1`, and the `name` of the row with index `2`. Then use `df.iat` to get the element at row `2`, column `2`. Explain when you would prefer `at` / `iat` over `loc` / `iloc`.

In [80]:
a = pd.read_csv("Online Sales Data.csv")

In [83]:
a.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2026-01-01,Home Appliances,Blender,9,69.99,629.91,Africa,PayPal
1,10002,2026-01-02,Books,Atomic Habits,8,16.99,135.92,Oceania,PayPal
2,10003,2026-01-02,Clothing,Yoga Pants,5,39.99,199.95,Asia,PayPal
3,10004,2026-01-05,Beauty Products,Perfume,9,74.99,674.91,North America,Credit Card
4,10005,2026-01-05,Beauty Products,Perfume,5,74.99,374.95,North America,Gift Card

In [ ]:
# use .at() to access a single element.

### Assignment 15: Adding a New Column

Add a new column named `salary` to the DataFrame from Assignment 5 with the values `[50000, 60000, 70000]`. Print the updated DataFrame.

In [86]:
data = pd.DataFrame(
    [
        {"name": "Rex", "age": 23, "city": "London"},
        {"name": "Champ", "age": 33, "city": "Toronto"},
        {"name": "Smoke", "age": 34, "city": "Los Santos"},
    ]
)

print(data)

    name  age        city
0    Rex   23      London
1  Champ   33     Toronto
2  Smoke   34  Los Santos

In [87]:
data["Salary"] = [50000, 60000, 70000]

In [88]:
print(data)

    name  age        city  Salary
0    Rex   23      London   50000
1  Champ   33     Toronto   60000
2  Smoke   34  Los Santos   70000

### Assignment 16: Removing a Column

Remove the `salary` column using `df.drop`.
1. First call `df.drop("salary")` without extra parameters. What error do you get and why? (Hint: the default `axis`.)
2. Fix it by using `axis=1`. Print `df` again. Is the column really gone?
3. Make the change permanent using `inplace=True`, and confirm by printing `df`.

In [91]:
data.drop("Salary", axis=1, inplace=True)

In [92]:
data

    name  age        city
0    Rex   23      London
1  Champ   33     Toronto
2  Smoke   34  Los Santos

### Assignment 17: Updating a Column

Increase every value in the `age` column by 1 (as if one year has passed) and store the result back in the same column. Print the DataFrame before and after.

In [93]:
data["age"] += 1

In [94]:
data

    name  age        city
0    Rex   24      London
1  Champ   34     Toronto
2  Smoke   35  Los Santos

### Assignment 18: Removing a Row

Drop the row with index `0` from the DataFrame permanently using `inplace=True`. Print the DataFrame and confirm only the remaining rows are present.

In [95]:
data.drop(0, inplace=True)

In [96]:
data

    name  age        city
1  Champ   34     Toronto
2  Smoke   35  Los Santos

### Assignment 19: Inspecting a DataFrame

Using the DataFrame read from `sales_data.csv`, print:
1. Its shape
2. Its column names
3. Its data types (`dtypes`)
4. Its summary using `info()`

In [98]:
data_frame = pd.read_csv("Online Sales Data.csv")

In [99]:
data_frame.shape

(500, 9)

In [102]:
data_frame.columns

Index(['Transaction ID', 'Date', 'Product Category', 'Product Name',
       'Units Sold', 'Unit Price', 'Total Revenue', 'Region',
       'Payment Method'],
      dtype='str')

In [103]:
data_frame.dtypes

Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object

In [104]:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    500 non-null    int64
 1   Date              500 non-null    str
 2   Product Category  500 non-null    str
 3   Product Name      500 non-null    str
 4   Units Sold        500 non-null    int64
 5   Unit Price        500 non-null    float64
 6   Total Revenue     500 non-null    float64
 7   Region            500 non-null    str
 8   Payment Method    500 non-null    str
dtypes: float64(2), int64(2), str(5)
memory usage: 35.3 KB

### Assignment 20: Statistical Summary

Use `describe()` on the sales DataFrame. From the output, identify the mean of `units_sold`, the maximum of `unit_price`, and the standard deviation of `total_revenue`. Why is the mean of `transaction_id` not a meaningful statistic?

In [105]:
data_frame.describe()

       Transaction ID  Units Sold  Unit Price  Total Revenue
count      500.000000  500.000000  500.000000     500.000000
mean     10250.500000    5.472000   52.026000     290.243280
std        144.481833    2.753248   38.421754     268.294693
min      10001.000000    1.000000   11.990000      11.990000
25%      10125.750000    3.000000   21.990000      95.677500
50%      10250.500000    6.000000   44.990000     199.950000
75%      10375.250000    8.000000   71.240000     401.212500
max      10500.000000   10.000000  199.990000    1799.910000

pandas.Series

### Assignment 21: Series vs. DataFrame Summary

In your own words (in a markdown cell), explain the difference between a Pandas Series and a Pandas DataFrame. Mention dimensionality, the index, and the kinds of data each can hold.

In [111]:
# Pandas series is a 1D data 
type(data_frame.loc[0:, "Transaction ID"])

pandas.Series

In [112]:
# Pandas Dataframe is a 2D data 
type(data_frame.loc[0:, ["Transaction ID", "Total Revenue"]])

pandas.DataFrame